### ISSUE TITLE
plyvel._plyvel.IOError: IO error: Invalid argument

### ISSUE THREAD

**Issue by jordynlaubscher** [graymauser/btcposbal2csv#14]
I am receiving the below error, please could you assist.

(envname) jordyn@DESKTOP-R6AIPP6:~/btcposbal2csv$ python btcposbal2csv.py /mnt/b/.Bitcoin/chainstate /home/jordyn/addresses_with_balance.csv
reading chainstate database
inmem
Traceback (most recent call last):
  File "btcposbal2csv.py", line 201, in <module>
    for address, sat_val, block_height in add_iter:
  File "btcposbal2csv.py", line 101, in in_mem
    types=get_types(in_args)):
  File "/home/jordyn/btcposbal2csv/utils.py", line 314, in parse_ldb
    db = plyvel.DB(fin_name, compression=None)  # Change with path to chainstate
  File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
  File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
plyvel._plyvel.IOError: IO error: /mnt/b/.Bitcoin/chainstate: Invalid argument

**Comment by space-mvc** [comment]
try upgrading Leveldb and possibly Python

**Comment by graymauser** [comment]
Please provide more context, namely the version of the python and the libraries used (plyvel, hashlib..)

**Comment by Fzoss** [comment]
I have the same problem,
using python2.7.18 , plyvel (1.3.0) , base58 (1.0.3) 
I can't install the hashlib and sqlite libraries, after checking they seem to be integrated in the newer python distributions

reading chainstate database
inmem
Traceback (most recent call last):
  File "btcposbal2csv.py", line 201, in <module>
    for address, sat_val, block_height in add_iter:
  File "btcposbal2csv.py", line 101, in in_mem
    types=get_types(in_args)):
  File "/mnt/d/btcposbal2csv-master/utils.py", line 314, in parse_ldb
    db = plyvel.DB(fin_name, compression=None)  # Change with path to chainstate
  File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
  File "plyvel/_plyvel.pyx", line 94, in plyvel._plyvel.raise_for_status
plyvel._plyvel.Error: Invalid argument: D:Bitcoinchainstate: does not exist (create_if_missing is false)

**Comment by a4r7gc4ttfwsqcey** [comment]
Looks like he seems to be using Windows Subsystem for Linux, that file system might not be compatible

I tried it myself using WSL and ran into the same problem. But a normal linux machine worked fine.
