### ISSUE TITLE
Getting Invalid argument error.

### ISSUE THREAD

**Issue by mrbrownstone07** [graymauser/btcposbal2csv#32]
![Capture](https://user-images.githubusercontent.com/45260879/167423448-21c71f71-ab8e-412b-88a8-9281da116d41.PNG)

I have chainstate data on my windows machine, I am trying to run the script from WSL. But I am getting the following error. 

reading chainstate database
inmem
Traceback (most recent call last):
  File "btcposbal2csv.py", line 201, in <module>
    for address, sat_val, block_height in add_iter:
  File "btcposbal2csv.py", line 101, in in_mem
    types=get_types(in_args)):
  File "/mnt/e/Finrocks/btc/btcposbal2csv/utils.py", line 323, in parse_ldb
    db = plyvel.DB(fin_name, compression=None)  # Change with path to chainstate
  File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
  File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
plyvel._plyvel.IOError: IO error: /mnt/f/Bitcoin/chainstate/: Invalid argument

**Comment by graymauser** [comment]
Thank you for the issue, I'll look into it (I usually run the script in `WSL` so that should not be the problem).

Please check the following:
- you have stopped the bitcoin core before running this script
- you are using python 2.7
