### ISSUE TITLE
error

### ISSUE THREAD

**Issue by granula** [graymauser/btcposbal2csv#5]
C:\btc>"C:\Python27\python.exe" convert2ripemd160.py All.csv
14miac6nnm9FWyew3CqG995ysHPSKfoXYP,ripemd
Traceback (most recent call last):
  File "convert2ripemd160.py", line 41, in <module>
    process(args.csvin)
  File "convert2ripemd160.py", line 19, in process
    ripemd_bin = tocondensed(row.split(',')[0])
  File "convert2ripemd160.py", line 7, in tocondensed
    return base58.b58decode(add_or_pk)[1:-4]
  File "C:\Python27\lib\site-packages\base58.py", line 96, in b58decode
    acc = b58decode_int(v)
  File "C:\Python27\lib\site-packages\base58.py", line 83, in b58decode_int
    decimal = decimal * 58 + alphabet.index(char)
ValueError: substring not found

**Comment by graymauser** [comment]
Hi,
this appears to be a bug related to missing header in csv file.

Would you consider to post here a head of your csv file (like first 5 lines)? I'm bit bussy, right now, and having test case would be helpful (did you generate the csv file with the btcposbal2csv.py?)

Thanks
